version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ozon
      POSTGRES_USER: plan9t
      POSTGRES_PASSWORD: plan9t
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: hausthe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: plan9t
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: